#!/usr/bin/env python3
"""PostToolUse hook: check xyz_behavior project file compliance.

Covers all file types generated by the xyz-bt-facade-project skill:
  - tree/*_bt.py
  - runtime/_runtime_io.py
  - runtime/runtime_facade.py
  - infra/infra_manifest.py
  - infra/bb_ros_bridge.py
  - app/*_bt_node.py
  - scripts/*_bt_node.py
  - launch/*.launch
  - behaviours/actions.py
"""
import json
import os
import re
import sys

_HOOK = 'xyz_behavior_guard'

_PATTERN = re.compile(r'xyz_behavior/(?!log/).+\.(py|launch|xml)$')

_COMMENT_RE = re.compile(r'#[^\n]*')
_STRING_RE  = re.compile(r'("""[\s\S]*?"""|\'\'\'[\s\S]*?\'\'\'|"[^"\n]*"|\'[^\'\n]*\')')


def _strip_noise(src: str) -> str:
    """Remove string literals and comments to avoid false positives."""
    src = _STRING_RE.sub('""', src)
    src = _COMMENT_RE.sub('', src)
    return src


def check_runtime_io(content: str, file_path: str) -> list[str]:
    violations: list[str] = []
    clean = _strip_noise(content)

    # Must import BuzzerState from ros_robot_controller.msg, NOT ainex_interfaces.msg
    if re.search(r'from\s+ainex_interfaces\.msg\s+import', clean):
        violations.append(
            "❌ BuzzerState imported from ainex_interfaces.msg — must use ros_robot_controller.msg instead"
        )
    if re.search(r'BuzzerState', content) and not re.search(
        r'from\s+ros_robot_controller\.msg\s+import', clean
    ):
        violations.append(
            "❌ BuzzerState not imported from ros_robot_controller.msg"
        )

    return violations


def check_runtime_facade(content: str, file_path: str) -> list[str]:
    violations: list[str] = []
    clean = _strip_noise(content)

    if not re.search(r'class\s+\w+\s*\([^)]*XyzBTFacade[^)]*\)', clean):
        violations.append(
            "❌ Facade class does not inherit XyzBTFacade  →  class Foo(XyzBTFacade):"
        )

    return violations


def check_infra_manifest(content: str, file_path: str) -> list[str]:
    violations: list[str] = []

    if 'def build_infra_manifest(' not in content:
        violations.append("❌ Missing build_infra_manifest() function")
    if 'def write_infra_manifest(' not in content:
        violations.append("❌ Missing write_infra_manifest() function")

    return violations


def check_bb_ros_bridge(content: str, file_path: str) -> list[str]:
    violations: list[str] = []
    clean = _strip_noise(content)

    if not re.search(r'class\s+\w+BBBridge', clean):
        violations.append("❌ Missing XXXBBBridge class definition")
    if 'def start(' not in content:
        violations.append("❌ Missing start() method")

    return violations


def check_tree_bt(content: str, file_path: str) -> list[str]:
    """Check tree/*_bt.py compliance: bootstrap() present + companion _groot.xml exists."""
    violations: list[str] = []

    # Only check *_bt.py wiring files; skip __init__.py and other tree/ files
    if not file_path.endswith('_bt.py'):
        return violations

    if 'def bootstrap(' not in content:
        violations.append(
            "❌ Missing bootstrap() function  →  def bootstrap(facade, logger=None, tick_id_getter=None, ...)"
        )

    # Companion Groot XML must exist alongside this _bt.py (rule #11)
    xml_path = file_path.replace('_bt.py', '_groot.xml')
    if not os.path.exists(xml_path):
        xml_name = os.path.basename(xml_path)
        violations.append(
            f"❌ Missing companion Groot XML: {xml_name}  →  "
            f"generate from project_bt_groot.xml.tpl and keep in sync with this _bt.py"
        )

    return violations


def check_groot_xml(content: str, file_path: str) -> list[str]:
    violations: list[str] = []

    if not file_path.endswith('_groot.xml'):
        return violations           # skip __pycache__ or other xml if any

    try:
        import xml.etree.ElementTree as ET
        root_el = ET.fromstring(content)
    except Exception as e:
        violations.append(f"❌ Invalid XML: {e}")
        return violations

    # Must have main_tree_to_execute attribute
    if not root_el.get('main_tree_to_execute'):
        violations.append(
            "❌ Missing main_tree_to_execute attribute on <root>  →  "
            "<root main_tree_to_execute=\"{{PROJECT}}\">"
        )

    # Must have at least one <BehaviorTree> child
    if root_el.find('BehaviorTree') is None:
        violations.append("❌ No <BehaviorTree> element found")

    # Must have <TreeNodesModel> section
    if root_el.find('TreeNodesModel') is None:
        violations.append("❌ Missing <TreeNodesModel> section")

    # Companion _bt.py must exist (symmetric to check_tree_bt's xml check)
    bt_path = file_path.replace('_groot.xml', '_bt.py')
    if not os.path.exists(bt_path):
        bt_name = os.path.basename(bt_path)
        violations.append(
            f"❌ Missing companion tree file: {bt_name}  →  "
            f"create it to match this _groot.xml"
        )

    return violations


def check_app_bt_node(content: str, file_path: str) -> list[str]:
    violations: list[str] = []

    if 'def main(' not in content:
        violations.append("❌ Missing main() entry function")
    if 'snapshot_and_reset()' not in content:
        violations.append("❌ Missing adapter.snapshot_and_reset() — two-phase lock protocol Phase 1")
    if 'write_snapshot(' not in content:
        violations.append("❌ Missing adapter.write_snapshot() — two-phase lock protocol Phase 2")
    if 'rospkg.RosPack' not in content:
        violations.append("❌ Missing rospkg.RosPack().get_path('xyz_behavior') — standard _PKG_PATH pattern")

    return violations


def check_script_bt_node(content: str, file_path: str) -> list[str]:
    violations: list[str] = []
    clean = _strip_noise(content)

    if 'import main' not in content:
        violations.append("❌ Script entry point does not import main function")
    if 'rospkg.RosPack().get_path' not in content:
        violations.append("❌ Script entry point missing rospkg path setup")
    if 'sys.path.insert(' not in content:
        violations.append("❌ Script entry point missing sys.path.insert()")

    return violations


def check_launch(content: str, file_path: str) -> list[str]:
    violations: list[str] = []

    try:
        import xml.etree.ElementTree as ET
        ET.fromstring(content)
    except Exception as e:
        violations.append(f"❌ Invalid XML: {e}")

    return violations


def check_behaviours(content: str, file_path: str) -> list[str]:
    """Check XyzL2ActionNode compliance for project-specific behaviour nodes."""
    violations: list[str] = []
    clean = _strip_noise(content)

    # Empty file (no classes) is valid — project may not need custom behaviours
    if not re.search(r'class\s+', clean):
        return violations

    # XyzL2GaitActionNode is an accepted base too (project gait nodes inherit it to
    # get the shared gait pass-through plumbing). Kept as a widened pattern so a
    # future intermediate base does not silently false-positive every node.
    if not re.search(r'class\s+\w+\s*\([^)]*XyzL2\w*ActionNode[^)]*\)', clean):
        violations.append("❌ Behaviour class does not inherit XyzL2ActionNode / XyzL2GaitActionNode  →  class Foo(XyzL2ActionNode):")
    if not re.search(r'^\s{4}LEVEL\s*=', clean, re.MULTILINE):
        violations.append("❌ Missing class variable LEVEL  →  LEVEL = 'L2'")
    if not re.search(r'^\s{4}BB_LOG_KEYS\s*=', clean, re.MULTILINE):
        violations.append("❌ Missing class variable BB_LOG_KEYS  →  BB_LOG_KEYS = ['key1']")
    calls = re.findall(r'rospy\.\w+\s*\(', clean)
    if calls:
        samples = ', '.join(sorted(set(calls))[:3])
        violations.append(
            f"❌ Direct rospy.*() call: {samples}  →  use call_facade() / RuntimeFacade instead"
        )

    return violations


# ── File pattern → check function map ─────────────────────────────────────
_CHECK_MAP = [
    ('runtime/_runtime_io.py',     check_runtime_io),
    ('runtime/runtime_facade.py',  check_runtime_facade),
    ('infra/infra_manifest.py',    check_infra_manifest),
    ('infra/bb_ros_bridge.py',     check_bb_ros_bridge),
    ('tree/',                      check_tree_bt),
    ('_groot.xml',                 check_groot_xml),
    ('app/',                       check_app_bt_node),
    ('scripts/',                   check_script_bt_node),
    ('launch/',                    check_launch),
    ('behaviours/',                check_behaviours),
]


def _log(action, file_path, violations, data):
    try:
        import guard_log
        if violations:
            guard_log.log_violations(_HOOK, action, file_path, violations, data)
        else:
            guard_log.log_clean(_HOOK, file_path, data)
    except Exception:
        pass


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except Exception:
        sys.exit(0)

    if data.get("tool_name", "") not in ("Write", "Edit"):
        sys.exit(0)

    file_path = data.get("tool_input", {}).get("file_path", "")
    if not _PATTERN.search(file_path):
        sys.exit(0)

    try:
        with open(file_path, "r", encoding="utf-8") as fh:
            content = fh.read()
    except Exception:
        sys.exit(0)

    all_violations = []
    matched_checks = []
    for pat, check_fn in _CHECK_MAP:
        if pat in file_path:
            matched_checks.append(pat)
            all_violations.extend(check_fn(content, file_path))

    if not matched_checks:
        sys.exit(0)

    if not all_violations:
        _log('pass', file_path, (), data)
        sys.exit(0)

    _log('warned', file_path, all_violations, data)

    lines = "\n".join(f"  {v}" for v in all_violations)
    context = (
        f"[xyz_behavior guard · compliance check] {file_path} has {len(all_violations)} violation(s):\n"
        f"{lines}\n"
        "Please fix the issues above before proceeding — must comply with the xyz-bt-facade-project skill."
    )
    print(json.dumps({"additionalContext": context}))
    sys.exit(0)


if __name__ == '__main__':
    main()
