#!/usr/bin/env python3
"""PreToolUse hook: inject conventions reminder before writing to xyz_behavior project files.

Covers all file types generated by the xyz-bt-facade-project skill.
"""
import json
import re
import sys

_PATTERN = re.compile(r'xyz_behavior/(?!log/).+\.(py|launch|xml)$')

_FILE_TYPE_HINTS = {
    'runtime/_runtime_io.py': (
        '[xyz_behavior guard · _runtime_io.py]\n'
        '  1. BuzzerState must be imported from ros_robot_controller.msg (not ainex_interfaces.msg)\n'
        '  2. Class name must be _RuntimeIO\n'
        '  3. Methods: enable_gait / disable_gait / stop_gait / set_step / run_action / publish_buzzer\n'
        '  4. See skill template assets/templates/_runtime_io.py.tpl'
    ),
    'runtime/runtime_facade.py': (
        '[xyz_behavior guard · runtime_facade.py]\n'
        '  1. Facade class must inherit XyzBTFacade\n'
        '  2. All abstract methods must be implemented (stub unused ones too)\n'
        '  3. All ROS I/O must be delegated to _RuntimeIO\n'
        '  4. See skill template assets/templates/runtime_facade.py.tpl'
    ),
    '_groot.xml': (
        '[xyz_behavior guard · tree/*_groot.xml]\n'
        '  1. Co-authoritative with companion *_bt.py — you wrote this file, so update *_bt.py to match\n'
        '  2. <root main_tree_to_execute="{{PROJECT}}"> must match BehaviorTree ID\n'
        '  3. <TreeNodesModel> must declare every node ID used in the tree'
    ),
    'tree/': (
        '[xyz_behavior guard · tree/*_bt.py]\n'
        '  1. Must define bootstrap(facade, logger=None, tick_id_getter=None, ...) function\n'
        '  2. Nodes with CONFIG_DEFAULTS must expand to explicit kwargs + "# CONFIG_DEFAULTS — override to tune:" comment\n'
        '  3. For L1/L2 nodes, pass logger+tick_id_getter via kw and facade via kw_f\n'
        '  4. See skill templates: project_bt.py.tpl (tree wiring) + project_bt_groot.xml.tpl (Groot XML)\n'
        '  5. Co-authoritative with companion _groot.xml — you wrote this file, so update _groot.xml to match'
    ),
    'app/': (
        '[xyz_behavior guard · app/*_bt_node.py]\n'
        '  1. Must define main() function\n'
        "  2. Log dir: _LOG_DIR = os.path.join(_PKG_PATH, 'log') (shared dir, not per-project subdir)\n"
        '  3. Two-phase lock: with lock: snap = adapter.snapshot_and_reset(); ...; adapter.write_snapshot(snap, tick_id)\n'
        '  4. See skill template assets/templates/bt_node.py.tpl'
    ),
    'infra/': (
        '[xyz_behavior guard · infra/*.py]\n'
        '  infra_manifest.py — must define build_infra_manifest() and write_infra_manifest()\n'
        '  bb_ros_bridge.py  — must define XXXBBBridge class with start(rate_hz) method\n'
        '  bt_exec_controller.py / tree_publisher.py — standard copies; see an existing project for reference\n'
    ),
    'launch/': (
        '[xyz_behavior guard · launch/*.launch]\n'
        '  1. node name must match PROJECT name (no _bt_node suffix)\n'
        '  2. type points to script under scripts/\n'
        '  3. Must be valid XML\n'
    ),
    'scripts/': (
        '[xyz_behavior guard · scripts/*_bt_node.py]\n'
        '  1. Thin entry file (3-5 lines)\n'
        '  2. Add PKG_PATH to sys.path\n'
        '  3. Import main from the corresponding app module\n'
        '  4. See scripts/approachhoop_bt_node.py for reference'
    ),
    'behaviours/': (
        '[xyz_behavior guard · behaviours/actions.py]\n'
        '  1. Each behaviour class must inherit XyzL2ActionNode\n'
        '  2. Must have class variables LEVEL and BB_LOG_KEYS\n'
        '  3. Must not call rospy.*() directly\n'
        '  4. File may be empty if no custom behaviour nodes are needed'
    ),
}


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except Exception:
        sys.exit(0)

    tool_name = data.get("tool_name", "")
    if tool_name not in ("Write", "Edit"):
        sys.exit(0)

    file_path = data.get("tool_input", {}).get("file_path", "")
    if not _PATTERN.search(file_path):
        sys.exit(0)

    # Find best matching hint
    hint = None
    for pattern_key, message in _FILE_TYPE_HINTS.items():
        if pattern_key in file_path:
            hint = message
            break

    if hint is None:
        hint = (
            '[xyz_behavior guard · pre-write reminder]\n'
            'Detected write to xyz_behavior/ project file.\n'
            'Ensure compliance with the xyz-bt-facade-project skill.\n'
            'Consult the skill templates if in doubt.'
        )

    print(json.dumps({"additionalContext": hint}))
    sys.exit(0)


main()
