#!/usr/bin/env python3
# encoding: utf-8
# Date:2023/07/10
import rospy
from ainex_kinematics.motion_manager import MotionManager

rospy.init_node('jump_control_demo')
# 调用上位机生成的动作, 参数为动作组存储的路径(call the action generated by PC software, and the parameter is the path for storing action group)
motion_manager = MotionManager('/home/ubuntu/software/ainex_controller/ActionGroups/triplejump')

motion_manager.run_action('triplejump03')
motion_manager.run_action('triplejump03')
motion_manager.run_action('triplejump04')
