#!/usr/bin/env python3
# encoding: utf-8
# Date:2023/07/10
import time
import rospy
from ainex_kinematics.gait_manager import GaitManager
from ainex_kinematics.motion_manager import MotionManager

rospy.init_node('gait_control_demo')
# 调用上位机生成的动作, 参数为动作组存储的路径(call the action generated by PC software, and the parameter is the path for storing action group)
motion_manager = MotionManager('/home/ubuntu/software/ainex_controller/ActionGroups/weightlifting')
# 步态控制库(gait control library)
gait_manager = GaitManager()
time.sleep(0.2)

gait_manager.disable()
motion_manager.run_action('weight_lift_up_5')

#Set default gait settings
gait_param = gait_manager.get_gait_param() 

gait_param['init_x_offset'] = 0.0
gait_param['init_y_offset'] = 0.0
gait_param['init_z_offset'] = 0.008

gait_param['init_roll_offset'] = 0.0
gait_param['init_pitch_offset'] = 0.0
gait_param['init_yaw_offset'] = 0.0

# period_time, dsp_ratio, y_swap_amplitude
dsp = [300, 0.2, 0.02] #dsp = [400, 0.2, 0.02]

gait_param['step_fb_ratio'] = 0.028
gait_param['z_swap_amplitude'] = 0.006
gait_param['pelvis_offset'] = 5.0

gait_param['x_move_amplitud'] = 0.02
gait_param['y_move_amplitude'] = 0.0
gait_param['z_move_amplitude'] = 0.01

gait_param['angle_move_amplitude'] = 0.0
gait_param['arm_swing_gain'] = 0.5
gait_param['hip_pitch_offset'] = 0

gait_param['body_height'] = 0.06

#第4个参数-1，是向右转弯1档，最大3
gait_manager.set_step(dsp, 0.02, 0, -0.3, gait_param, arm_swap=0, step_num=11)
time.sleep(2)

gait_manager.disable()
motion_manager.run_action('weight_lift_headup_6')
#motion_manager.run_action('weight_lift_headup_6')

#Set default gait settings
gait_param = gait_manager.get_gait_param() 

gait_param['init_x_offset'] = 0.0
gait_param['init_y_offset'] = 0.0
gait_param['init_z_offset'] = 0.008

gait_param['init_roll_offset'] = 0.0
gait_param['init_pitch_offset'] = 0.0
gait_param['init_yaw_offset'] = 0.0

# period_time, dsp_ratio, y_swap_amplitude
dsp = [300, 0.2, 0.02] #dsp = [400, 0.2, 0.02]

gait_param['step_fb_ratio'] = 0.028
gait_param['z_swap_amplitude'] = 0.006
gait_param['pelvis_offset'] = 5.0

gait_param['x_move_amplitud'] = 0.01
gait_param['y_move_amplitude'] = 0.0
gait_param['z_move_amplitude'] = 0.01

gait_param['angle_move_amplitude'] = -0.1
gait_param['arm_swing_gain'] = 0.5
gait_param['hip_pitch_offset'] = 0

gait_param['body_height'] = 0.06

gait_manager.set_step(dsp, 0.02, 0, 0.0, gait_param, arm_swap=0, step_num=15)
time.sleep(2)

gait_manager.disable()
motion_manager.run_action('weight_lift_end')
#motion_manager.run_action('weight_lift_end')
time.sleep(2)
