####### low_speed #######
float32 low_speed_forward_offset
float32 low_speed_backward_offset
float32 low_speed_move_left_offset
float32 low_speed_move_right_offset

####### medium_speed #####
float32 medium_speed_forward_offset
float32 medium_speed_backward_offset
float32 medium_speed_move_left_offset
float32 medium_speed_move_right_offset

########## high_speed ########
float32 high_speed_forward_offset
float32 high_speed_backward_offset
float32 high_speed_move_left_offset
float32 high_speed_move_right_offset
