"""Rules for xyz_behavior project files, generated by the xyz-bt-facade-project skill.

Function bodies are lifted verbatim from xyz_behavior_guard. See bt_lib_rules for why
the imports are aliased and why `from __future__ import annotations` is load-bearing --
this module is the one with the 16 `list[str]` annotations that would otherwise raise
TypeError on the container's Python 3.8.
"""
from __future__ import annotations

import os
import re

from guardlib.text_utils import strip_noise as _strip_noise

def check_runtime_io(content: str, file_path: str) -> list[str]:
    violations: list[str] = []
    clean = _strip_noise(content)

    # Must import BuzzerState from ros_robot_controller.msg, NOT ainex_interfaces.msg
    if re.search(r'from\s+ainex_interfaces\.msg\s+import', clean):
        violations.append(
            "❌ BuzzerState imported from ainex_interfaces.msg — must use ros_robot_controller.msg instead"
        )
    if re.search(r'BuzzerState', content) and not re.search(
        r'from\s+ros_robot_controller\.msg\s+import', clean
    ):
        violations.append(
            "❌ BuzzerState not imported from ros_robot_controller.msg"
        )

    return violations

def check_runtime_facade(content: str, file_path: str) -> list[str]:
    violations: list[str] = []
    clean = _strip_noise(content)

    if not re.search(r'class\s+\w+\s*\([^)]*XyzBTFacade[^)]*\)', clean):
        violations.append(
            "❌ Facade class does not inherit XyzBTFacade  →  class Foo(XyzBTFacade):"
        )

    return violations

def check_tree_bt(content: str, file_path: str) -> list[str]:
    """Check tree/*_bt.py compliance: bootstrap() present + companion _groot.xml exists."""
    violations: list[str] = []

    # Only check *_bt.py wiring files; skip __init__.py and other tree/ files
    if not file_path.endswith('_bt.py'):
        return violations

    if 'def bootstrap(' not in content:
        violations.append(
            "❌ Missing bootstrap() function  →  def bootstrap(facade, logger=None, tick_id_getter=None, ...)"
        )

    # Companion Groot XML must exist alongside this _bt.py (rule #11)
    xml_path = file_path.replace('_bt.py', '_groot.xml')
    if not os.path.exists(xml_path):
        xml_name = os.path.basename(xml_path)
        violations.append(
            f"❌ Missing companion Groot XML: {xml_name}  →  "
            f"generate from project_bt_groot.xml.tpl and keep in sync with this _bt.py"
        )

    return violations

def check_groot_xml(content: str, file_path: str) -> list[str]:
    violations: list[str] = []

    if not file_path.endswith('_groot.xml'):
        return violations           # skip __pycache__ or other xml if any

    try:
        import xml.etree.ElementTree as ET
        root_el = ET.fromstring(content)
    except Exception as e:
        violations.append(f"❌ Invalid XML: {e}")
        return violations

    # Must have main_tree_to_execute attribute
    if not root_el.get('main_tree_to_execute'):
        violations.append(
            "❌ Missing main_tree_to_execute attribute on <root>  →  "
            "<root main_tree_to_execute=\"{{PROJECT}}\">"
        )

    # Must have at least one <BehaviorTree> child
    if root_el.find('BehaviorTree') is None:
        violations.append("❌ No <BehaviorTree> element found")

    # Must have <TreeNodesModel> section
    if root_el.find('TreeNodesModel') is None:
        violations.append("❌ Missing <TreeNodesModel> section")

    # Companion _bt.py must exist (symmetric to check_tree_bt's xml check)
    bt_path = file_path.replace('_groot.xml', '_bt.py')
    if not os.path.exists(bt_path):
        bt_name = os.path.basename(bt_path)
        violations.append(
            f"❌ Missing companion tree file: {bt_name}  →  "
            f"create it to match this _groot.xml"
        )

    return violations

def check_app_bt_node(content: str, file_path: str) -> list[str]:
    violations: list[str] = []

    if 'def main(' not in content:
        violations.append("❌ Missing main() entry function")
    if 'snapshot_and_reset()' not in content:
        violations.append("❌ Missing adapter.snapshot_and_reset() — two-phase lock protocol Phase 1")
    if 'write_snapshot(' not in content:
        violations.append("❌ Missing adapter.write_snapshot() — two-phase lock protocol Phase 2")
    if 'rospkg.RosPack' not in content:
        violations.append("❌ Missing rospkg.RosPack().get_path('xyz_behavior') — standard _PKG_PATH pattern")

    return violations

def check_script_bt_node(content: str, file_path: str) -> list[str]:
    violations: list[str] = []
    clean = _strip_noise(content)

    if 'import main' not in content:
        violations.append("❌ Script entry point does not import main function")
    if 'rospkg.RosPack().get_path' not in content:
        violations.append("❌ Script entry point missing rospkg path setup")
    if 'sys.path.insert(' not in content:
        violations.append("❌ Script entry point missing sys.path.insert()")

    return violations

def check_launch(content: str, file_path: str) -> list[str]:
    violations: list[str] = []

    try:
        import xml.etree.ElementTree as ET
        ET.fromstring(content)
    except Exception as e:
        violations.append(f"❌ Invalid XML: {e}")

    return violations

def check_behaviours(content: str, file_path: str) -> list[str]:
    """Check XyzL2ActionNode compliance for project-specific behaviour nodes."""
    violations: list[str] = []
    clean = _strip_noise(content)

    # Empty file (no classes) is valid — project may not need custom behaviours
    if not re.search(r'class\s+', clean):
        return violations

    # XyzL2GaitActionNode is an accepted base too (project gait nodes inherit it to
    # get the shared gait pass-through plumbing). Kept as a widened pattern so a
    # future intermediate base does not silently false-positive every node.
    if not re.search(r'class\s+\w+\s*\([^)]*XyzL2\w*ActionNode[^)]*\)', clean):
        violations.append("❌ Behaviour class does not inherit XyzL2ActionNode / XyzL2GaitActionNode  →  class Foo(XyzL2ActionNode):")
    if not re.search(r'^\s{4}LEVEL\s*=', clean, re.MULTILINE):
        violations.append("❌ Missing class variable LEVEL  →  LEVEL = 'L2'")
    if not re.search(r'^\s{4}BB_LOG_KEYS\s*=', clean, re.MULTILINE):
        violations.append("❌ Missing class variable BB_LOG_KEYS  →  BB_LOG_KEYS = ['key1']")
    calls = re.findall(r'rospy\.\w+\s*\(', clean)
    if calls:
        samples = ', '.join(sorted(set(calls))[:3])
        violations.append(
            f"❌ Direct rospy.*() call: {samples}  →  use call_facade() / RuntimeFacade instead"
        )

    return violations
